from fastapi import APIRouter

router = APIRouter()

from ...services.nasa_services import (
    get_apod,
    get_asteroid_feed,
    get_asteroid_lookup,
    get_asteroid_browse,
    get_donki_cme,
    get_donki_analysis,
    get_donki_gst,
    get_donki_ips,
    get_donki_flr,
    get_donki_sep,
    get_donki_mpc,
    get_donki_rbe,
    get_donki_hss,
    get_donki_wsa_enlil_simulation,
    get_donki_notification,
    get_exoplanet,
    get_gibs,
    get_insight,
    get_image_library,
    get_insight_assest,
    get_insight_metadata,
    get_insight_caption,
    get_osdr,
    get_cneos,
    get_cneos_nhats,
    get_cneos_scout,
    get_cneos_sentry,
    get_techport,
    get_tle_api,
    get_mission_design,
    get_tech_transfer,
    get_epic,
    get_nasatrek,
)
